### ISSUE TITLE
JUnit @BeforeClass/@AfterClass as neccessary cleanup

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#10]
In our project the unit tests cannot be run repetitiously without resetting the state through `@AfterClass` and `@BeforeClass`.
peass does not run these functions between repetitions.
I understand that this is sometimes counterproductive to measurement speed.
Is it possible to get this feature as an option?

**Comment by DaGeRe** [comment]
Yes, we'll implement this and give you an update when it works.

**Comment by DaGeRe** [comment]
I've implemented a basic version in KoPeMe, you just need to set `executeBeforeClassInMeasurement = true` in the `@PerformanceTest` annotation (https://github.com/DaGeRe/KoPeMe/commit/7179eb9912bcf67007973c9a8923f904a2d07485). Would it be possible that you try this once manually before I add this to Peass and Peass-CI?
