### ISSUE TITLE
testGoal Parameter in den Optionen

### ISSUE THREAD

**Issue by alex-iotiq** [DaGeRe/peass-ci#11]
Es fehlt die Möglichkeit einen testGoal im Plugin anzugeben, genauso wie in peass https://github.com/DaGeRe/peass/issues/22.

**Comment by DaGeRe** [comment]
Danke für den Hinweis, das sollte jetzt mit https://github.com/DaGeRe/peass-ci/commit/114a55f1cea4359f8d53a5af0d1ea91e42cda928 gehen.

**Comment by alex-iotiq** [comment]
Bei mir tritt ein weiteres Problem auf. Der testGoal Parameter wird nach dem speichern auf "test" zurückgesetzt.

**Comment by DaGeRe** [comment]
Danke für den Hinweis, es fehlte eine Annotation: https://github.com/DaGeRe/peass-ci/commit/984c79da4ebab1dce211d00e3e3ab48024d5509a Kannst Du es nochmal probieren?

**Comment by DaGeRe** [comment]
Das funktioniert nach Rücksprache mit @alex-iotiq.
