### ISSUE TITLE
Test against last tested commit

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#12]
Since the performance testing takes quite long it might not be useful to trigger it for every build, instead for example something like once per night.
If triggered in that way it would be neccessary to run peass not against a statically defined version diff but instead against the last version that was tested by peass before.

**Comment by DaGeRe** [comment]
With commit https://github.com/DaGeRe/peass-ci/commit/6a38cd223a5fb347499043ccf30d6039b00b60e3, this should work now if `nightlyBuild` is activated. Could you test it?
