### ISSUE TITLE
Support execution of JMH-Tests from Jenkins

### ISSUE THREAD

**Issue by DaGeRe** [DaGeRe/peass-ci#14]
There should be a separate pipeline step measureJMH, which starts the measurement of JMH tests.

**Comment by mai13drd** [comment]
Now, in MeasureVersionBuilder a boolean 'measureJMH' exists which can be set in the pipeline configuration. If true, JmhTestTransformer and JmhTestExecutor are set to be used for measurements. This allows to use JMH-Tests for performance measurements.
To set 'measureJMH' add 'measureJMH: true' to the measure build-step.

**Comment by mai13drd** [comment]
For a non-pipeline-job, you can activate `measureJMH` in a checkbox inside the advanced settings for the `Measure Version Performance` buildstep.

**Comment by DaGeRe** [comment]
This works now, thanks!
