### ISSUE TITLE
Make clean Remeasurement possible

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#16]
Maybe this is mostly an issue for the current early stage:
Available data, i.e. the includes, or already instrumented tests don't change if you do a rebuild. To circumvent that you'd have to make a new jenkins item or delete the results of specific peass stages by hand. It would be useful to have possibilities of deleting some or all results through some jenkins menu item.

**Comment by DaGeRe** [comment]
Thanks for the idea, this should work since https://github.com/DaGeRe/peass-ci/commit/60d36ad510f9a0e7f1a16dea192de5ae4c2a557e, can you confirm this?

**Comment by Schattensilber** [comment]
Works as requested.
