### ISSUE TITLE
Use of JMH-benchmarks requires source code instrumentation 

### ISSUE THREAD

**Issue by mai13drd** [DaGeRe/peass-ci#27]
If JMH-benchmarks are used for measurements, the field `Source instrumentation` inside the job configuration must be set, since JMH in combination with AspectJ-instrumentation does not work yet.
This should be fixed or at least reported to the user.

**Comment by DaGeRe** [comment]
The jmh execution had configuration problems with using AspectJ. With the newest develop version, this works now. Please reopen if this is still a problem.
