### ISSUE TITLE
Delete peass-Cache also deletes measurement details

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#33]
The delete cache ability is there mainly to allow new measurements with a changed peass-version or configuration. The old measurement is often still valid, but the details (through the Inspect Measurements link) are not available after deleting the cache.
Would it be possible to hold these results available?

**Comment by DaGeRe** [comment]
Thanks for the hint, Peass-CI was storing the path to the (deletable) file instead the data in the runs. Since d7a1d91, the javascript data are saved and all runs should contain their measurement data (and deleting the runs will also delete this stored data).
