### ISSUE TITLE
Extension of pipeline helptext for includes

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#38]
The text there is helpful, only please add the notation for maven submodules: submodule$path.to.Test#*

**Comment by DaGeRe** [comment]
Thanks for the hint, it is separated by §, this is now is described in https://github.com/DaGeRe/peass-ci/commit/3ab300e058581ea30eb0e8d29604572f4496d41f

**Comment by Schattensilber** [comment]
So it seems that was not the cause of the problem, not sure it's actually necessary?

**Comment by DaGeRe** [comment]
Yes, but this was an internal error in Peass, which should now be fixed: https://github.com/DaGeRe/peass/commit/dacf85263073a52d2931bd8d06dfc49c9ad9838f
