### ISSUE TITLE
Jenkins Build passes though test selection has exception

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#55]
In some cases when the test selection ends with an error the jenkins build is still green. There should be a easily visible warning that something has gone wrong. 

Concrete maven error is:
[ERROR] /var/jenkins_home/workspace/GeoMap-PermanEnt-daily_fullPeass/GeoMap-PermanEnt-daily/geomap-backend-objektservice/src/main/java/immo/geomap/backend/objektservice/impl/bauprojekte/BauprojekteWiedervorlagenServiceImpl.java:[491,78] cannot find symbol

Probably a plugin caused problem.

**Comment by DaGeRe** [comment]
Thanks for the hint. It currently seems like this was a compile error in your project, still, Peass should inform you about the change. This should work in latest develop version (starting with https://github.com/DaGeRe/peass/commit/6bc5e3784729ad7afb8c366d1492ee974725b434). Could you check this?
